version: '{build}-{branch}'
before_build:
- cmd: cd build
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: artifacts\*.nupkg
  name: nupkg
  type: File
nuget:
  account_feed: true
  project_feed: true
deploy:
- provider: NuGet
  name: NuGet
  api_key:
    secure: 4Vg2LsDg84QSE6hpB1KKigaSpoywvjy8XDAHrv/NB5PTF7VLCUIQkQZMa6qOTxIs
  artifact: nupkg
  on:
    branch: master
- provider: GitHub
  name: GitHub
  artifact: nupkg
  on:
    branch: master
- provider: NuGet
  name: NuGet (pre release)
  api_key:
    secure: 4Vg2LsDg84QSE6hpB1KKigaSpoywvjy8XDAHrv/NB5PTF7VLCUIQkQZMa6qOTxIs
  artifact: nupkg
  on:
    branch: v.*
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
  artifact: nupkg
  symbol_server: https://www.myget.org/F/dittodhole/symbols/api/v2/package