version: '{build}-{branch}'
skip_tags: true
build_script:
- ps: .\build\build.ps1
after_build:
- cmd: appveyor PushArtifact "artifacts/*"
test: off
deploy:
- provider: NuGet
  name: NuGet
  api_key:
    secure: 4Vg2LsDg84QSE6hpB1KKigaSpoywvjy8XDAHrv/NB5PTF7VLCUIQkQZMa6qOTxIs
  artifact: artifacts/*.nupkg
  on:
    branch: master
- provider: NuGet
  name: NuGet (pre release)
  api_key:
    secure: 4Vg2LsDg84QSE6hpB1KKigaSpoywvjy8XDAHrv/NB5PTF7VLCUIQkQZMa6qOTxIs
  artifact: artifacts/*.nupkg
  on:
    branch: v.*
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
  artifact: artifacts/*.nupkg
  symbol_server: https://www.myget.org/F/dittodhole/symbols/api/v2/package