version: '{build}-{branch}'
skip_tags: true
before_build:
- cmd: cd build
build_script:
- ps: .\build.ps1
artifacts:
- path: artifacts\Contrib.MSBuild.TypeLibrary.*.nupkg
  name: Contrib.MSBuild.TypeLibrary.nupkg
  type: File
test: off
deploy:
- provider: NuGet
  name: NuGet
  api_key:
    secure: 4Vg2LsDg84QSE6hpB1KKigaSpoywvjy8XDAHrv/NB5PTF7VLCUIQkQZMa6qOTxIs
  artifact: artifacts\Contrib.MSBuild.TypeLibrary.*.nupkg
  on:
    branch: master
- provider: GitHub
  artifact: artifacts\Contrib.MSBuild.TypeLibrary.*.nupkg
  on:
    branch: master
- provider: NuGet
  name: NuGet (pre release)
  api_key:
    secure: 4Vg2LsDg84QSE6hpB1KKigaSpoywvjy8XDAHrv/NB5PTF7VLCUIQkQZMa6qOTxIs
  artifact: artifacts\Contrib.MSBuild.TypeLibrary.*.nupkg
  on:
    branch: v.*
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
  artifact: artifacts\Contrib.MSBuild.TypeLibrary.*.nupkg
  symbol_server: https://www.myget.org/F/dittodhole/symbols/api/v2/package